### ISSUE TITLE
Does this component compatible for Linux server?

### ISSUE THREAD

**Issue by yufeiqi** [LazZiya/ImageResize#1]
Hi
Thanks for the component, it do help lots of people to resize and change images easier,
have you encounter any issue when it run on Linux server with .net core 2.2?
the error message is about gdi+ issue, about 1 month ago.
Finally I used the sixlabour.imagesharp. but it still in progress, no publish version yet, and no watermark feature.
help you can fix the issue.
thanks 
Phil Yu

**Comment by LazZiya** [comment]
Hi @yufeiqi 

This package is depending on `System.Drawing.Common`, which is a cross platform GDI+ graphic processing package. And in order for it to work on Linux/Ubuntu some native libraries must be installed :

````
sudo apt install libc6-dev 
sudo apt install libgdiplus
````
Actually I didn't test it on linux server yet, but I will keep this issue open till I do the test then I will provide more details or publish a fix.

Best,
Ziya

**Comment by Khan0z** [comment]
on linux , an exceptions was throw:


Parameter is not valid. at System.Drawing.Bitmap.SetResolution ............

**Comment by srcmkr** [comment]
Set ImageResize.cs, Line 206 to
`outputImage.SetResolution(72, 72);`
and it works on linux (img.HorizontalResolution, img.VerticalResolution are both 0 on linux and there comes the exception)

**Comment by LazZiya** [comment]
Thank you @Khan0z and @srcmkr for pointing this issue and sorry for the long delay :( 

Finally I did my tests on ubuntu and managed to fix it as pointed by @srcmkr 👍🏽 

The fixed version will be released soon...

Bets Regards,
Ziya

**Comment by srcmkr** [comment]
Indeed a better fix that the hardcoded one ;)
Do you have plans for updates on the nuget?

**Comment by LazZiya** [comment]
The update will come within 1~2 weeks, just doing some more tests before the release.

**Comment by LazZiya** [comment]
Fix provided in [v4.0](https://github.com/LazZiya/ImageResize/releases/tag/v4.0), available in [nuget](https://www.nuget.org/packages/LazZiya.ImageResize/4.0.0).

BR,
Ziya
