### ISSUE TITLE
There is an issue that we are applying different value of Opacity on watermark logo but transparency is not changing 

### ISSUE THREAD

**Issue by AnkitPatel1996** [LazZiya/ImageResize#14]
Applying different value of Opacity on watermark logo but transparency is not changing

````cs
using (var img = Image.FromStream(stream))
{
    var imOps = new ImageWatermarkOptions 
    {
        Opacity = 35,
        Location = TargetSpot.Center
    };
    img.ScaleAndCrop(600, 300)
        .AddImageWatermark("wwwroot/images/icon.png", imOps)
        .SaveAs("wwwroot/upload/new-image.jpg");
}
````

**Comment by LazZiya** [comment]
can you share your images? just to check the image type and reproduce your issue.

**Comment by AnkitPatel1996** [comment]
The issue is solved with save jpg image.. but when We Scale & crop watermark image then opacity value is not change. Can you please suggest how we can crop logo image & change opacity ?

**Comment by LazZiya** [comment]
Create a new image file from the original image file, then apply it as watermark:

````cs
// create the new watermark as needed
using (var imgWatermark = Image.FromFile("wwwroot/images/icon.png"))
{
    imgWatermark.ScaleAndCrop(100, 100)
                .SaveAs("wwwroot/images/new-icon.png");
}

using (var img = Image.FromStream(stream))
{
    var imOps = new ImageWatermarkOptions 
    {
        Opacity = 35,
        Location = TargetSpot.Center
    };

    img.ScaleAndCrop(600, 300)
       // use the new icon as watermark
       .AddImageWatermark("wwwroot/images/new-icon.png", imOps)
       .SaveAs("wwwroot/upload/new-image.jpg");
}
````

**Comment by AnkitPatel1996** [comment]
We are getting System.ArgumentException: 'A Graphics object cannot be created from an image that has an indexed pixel format.  this error when we apply Image in Pixel format.
![png-transparent](https://user-images.githubusercontent.com/121091037/210344938-fc8a5059-fc2c-44b4-ab49-cd3036c8672a.png)

**Comment by LazZiya** [comment]
Issue fixed, you can use the latest version [v4.1.3](https://github.com/LazZiya/ImageResize/releases/tag/v4.1.3) available in [nuget](https://www.nuget.org/packages/LazZiya.ImageResize/4.1.3).

**Comment by AnkitPatel1996** [comment]
Thank you. It working by change latest version v4.1.3

**Comment by AnkitPatel1996** [comment]
![140580](https://user-images.githubusercontent.com/121091037/211755413-531b7510-67cd-4cbe-8c13-937dcae39d68.jpg)

**Comment by AnkitPatel1996** [comment]
We are getting rotated watermark for this type of image
![140580](https://user-images.githubusercontent.com/121091037/211756023-4878d292-ac14-4d5f-8c5e-dd3393734ef8.jpg)

**Comment by LazZiya** [comment]
This is caused due to some professional cameras _when you hold it horizontally or vertically_ it may store the rotation value in the image exif data and not really save the image as rotated! Read more [here](https://jdhao.github.io/2019/07/31/image_rotation_exif_info/).

Some fast and dirty solution;
- edit the image locally to save it with rotated orientation.
- try to resize the image before adding watermark.

I will work on a solution but can't promise to release it so soon.
