### ISSUE TITLE
AddFrameIf requires a thickness

### ISSUE THREAD

**Issue by DarkEyeDragon** [LazZiya/ImageResize#17]
**Describe the bug**
When adding a frame to an image with a fill it still requires a border thickness of at least 1point or no background is drawn.
This causes the image to be 1px larger than it should be.
**To Reproduce**
```
public Image ScaleByHeight(Image image, int height, bool fill)
{
            
    return image.ScaleByHeightIf(image.Size.Height > height, height).AddFrameIf(fill, height, height, new ImageFrameOptions
    {
        FillColor = Color.White,
        FrameShape = ImageFrameShape.Rectangle,
        Thickness = 1
    });
}
```
When setting Thickness to 0 no white background is drawn
**Expected behavior**
Allow a thickness of 0 when a fill color is passed

**Screenshots**
![image](https://user-images.githubusercontent.com/6131099/214818643-f46ec4c5-8d4e-4575-9c08-19555ab6bf91.png)

**Comment by LazZiya** [comment]
It is possible now to make frame thickness=0 and you still have the background fill applied.

Just download the latest version [v4.1.4](https://github.com/LazZiya/ImageResize/releases/tag/v4.1.4) from nuget.

**Comment by DarkEyeDragon** [comment]
Works like a charm, thanks.
