### ISSUE TITLE
Image has light gray borders after resizing

### ISSUE THREAD

**Issue by DarkEyeDragon** [LazZiya/ImageResize#23]
**Describe the bug**
After resizing the image there is a 1px wide border seemingly in the default border color

**To Reproduce**
```csharp
image.ScaleByHeight(300).SaveAs("file.jpg");
```

**Version**
- v1.4.1

**Expected behavior**
rescale without having the gray borders.

**Screenshots**
![image](https://github.com/LazZiya/ImageResize/assets/6131099/b79367af-a14b-426c-ba7c-ab8e59ccb56e)
Edges of the image are extended using Windows Paint. 

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by LazZiya** [comment]
I did several tries, and all worked as expected, no gray border even after extending the edges with windows paint:

![image](https://github.com/LazZiya/ImageResize/assets/22244584/a29c873e-ba3a-4be2-ba59-f2afbfd622bf)

Make sure the original image do not contain the border.

**Comment by DarkEyeDragon** [comment]
Wasn't able to get it sorted. But most likely something on my end then. Managed to get it working using another library.
