### ISSUE TITLE
free the memory used by the GDI bitmap object

### ISSUE THREAD

**Issue by mssalamati** [LazZiya/ImageResize#8]
you don`t **free** the memory used by the GDI bitmap object at the **Resize** function when you use **hBitmap**

you just follow [link ](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.bitmap.gethbitmap?redirectedfrom=MSDN&view=netcore-3.0#System_Drawing_Bitmap_GetHbitmap) to solve it.

> [System.Runtime.InteropServices.DllImport("gdi32.dll")]
> public static extern bool DeleteObject(IntPtr hObject);
> 
> private void DemonstrateGetHbitmap()
> {
>     Bitmap bm = new Bitmap("Picture.jpg");
>     IntPtr hBitmap = bm.GetHbitmap();
> 
>     // Do something with hBitmap.
>     DeleteObject(hBitmap);
> }

**Comment by LazZiya** [comment]
The [`Resize`](https://github.com/LazZiya/ImageResize/blob/c222ad102ebe1b957ab9e730600b575fa258c8cd/LazZiya.ImageResize/ImageResize.cs#L196-L236) method is used to return a resized `Image` object that will have some optional editing in the next steps (add text, image watermark, etc) then being saved by [`SaveAs`](https://github.com/LazZiya/ImageResize/blob/c222ad102ebe1b957ab9e730600b575fa258c8cd/LazZiya.ImageResize/SaveImage.cs#L18-L37) method. So freeing the memory at that step will delete the image object before editing/saving it in the next steps!

If you had a look at `SaveAs` method you will see the `img` is decorated by `using` statement, so the memory will be freed whenever the method exits `using` statement and after the image is being saved.

````cs
public static void SaveAs(this Image img, string path, int quality = 95)
{
    using (var myEncoderParameters = new EncoderParameters(1))
    {
        // ...
        using (var myEncoderParameter = new EncoderParameter(myEncoder, (long)quality))
        {
            // ...
            using (img)
            {
                // ....
                img.Save(path, myImageCodecInfo, myEncoderParameters);
            }
        }
    }
}
````

**Comment by LazZiya** [comment]
I believe the answer has provided a clarification for your issue.

Feel free to reopen if you have any more question.
